name: Mod Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup cache
        uses: actions/cache@v3.0.11
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Set build number
        run: sed -i "s/undefined/$GITHUB_RUN_NUMBER/g" gradle.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: Find Correct JAR
        id: find-jar
        run: |
          output="$(find build/libs/ -type f ! -name "*-dev.jar" ! -name "*-sources.jar" -printf "%f\n")"
          echo "jarname=$output" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        if: ${{ matrix.java == '21' }}
        uses: actions/upload-artifact@v4.1.0
        with:
          name: Artifact
          path: build/libs/
          retention-days: 64
          compression-level: 6 #same as GNU Gzip