name: Dev Builds

on:
  push:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "src/**"
      - "versions/**"
      - "settings.json"
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
#    # [FEATURE] MIXIN_AUDITOR
#    with:
#      mixin_audit: true
